In [33]:
import numpy as np

<h1  style="color: blue;">1.	Использование команд библиотеки NumPy</h1>
# 1.1 Создайте одномерный массив my_array, в котором по порядку все числа до 100, кратные 5

In [34]:
my_array = np.arange(5,101,5)
my_array

array([  5,  10,  15,  20,  25,  30,  35,  40,  45,  50,  55,  60,  65,
        70,  75,  80,  85,  90,  95, 100])

# 2.1   Из полученного массива получить массив с кратными 10 числами

In [35]:
my_array = my_array[my_array % 10 == 0]
my_array

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

# 3.1 Получить двумерный массив с двумя столбцами

In [36]:
two_columns = my_array.reshape(5,2)
two_columns

array([[ 10,  20],
       [ 30,  40],
       [ 50,  60],
       [ 70,  80],
       [ 90, 100]])

# 4.1.  Получите набор my_second_array, в котором все элементы меньше предыдущего исходного на 5

In [37]:
my_second_array =  my_array  - 5
my_second_array

array([ 5, 15, 25, 35, 45, 55, 65, 75, 85, 95])

# 5.1.  Соедините массивы, полученные в п. 3.1 и 4.1, горизонтально. Используйте .T для транспонирования матрицы.

In [38]:
final =  np.hstack((two_columns,my_second_array.reshape(5,2)))
final
final_T = final.T
final_T

array([[ 10,  30,  50,  70,  90],
       [ 20,  40,  60,  80, 100],
       [  5,  25,  45,  65,  85],
       [ 15,  35,  55,  75,  95]])

# 6.1.  Разделите 2 и 3 строку на 4 верхних строки my_array. Используйте .T для транспонирования матрицы

In [39]:
four = my_array[:4]
devided = final_T[1:3,:4] / four
devided_T = devided.T
devided_T

array([[2.   , 0.5  ],
       [2.   , 1.25 ],
       [2.   , 1.5  ],
       [2.   , 1.625]])

# 7.1.  Оставить только те значения, которые не изменились после деления

In [43]:
unchanged = devided[devided == 1]
print(unchanged)

[]


# 8.1.  Снова получить трехстрочный двумерный массив и поменять местами первую и третью строки

In [44]:
three_array = np.arange(1,28).reshape(3,-1)
three_array[1,5]= 12
three_array
swaped = three_array[::-1]
swaped

array([[19, 20, 21, 22, 23, 24, 25, 26, 27],
       [10, 11, 12, 13, 14, 12, 16, 17, 18],
       [ 1,  2,  3,  4,  5,  6,  7,  8,  9]])

# 9.1.  Получить среднее, медиану и стандартное отклонение для каждой строки, используя команды np.mean(), np.median(), np.std().

In [45]:
mean_values = np.mean(swaped, axis=1)
mean_values


array([23.        , 13.66666667,  5.        ])

In [46]:
median_values = np.median(swaped, axis=1)
median_values


array([23., 13.,  5.])

In [47]:
std_dev_values = np.std(swaped, axis=1)
std_dev_values

array([2.5819889 , 2.62466929, 2.5819889 ])

# 10.1.  Сделать нормализацию на максимальное значение вдоль строк, поделив каждый элемент массива на max() вдоль строк

In [48]:
normal_arr = three_array / np.max(three_array, axis = 1).reshape(-1,1)
normal_arr

array([[0.11111111, 0.22222222, 0.33333333, 0.44444444, 0.55555556,
        0.66666667, 0.77777778, 0.88888889, 1.        ],
       [0.55555556, 0.61111111, 0.66666667, 0.72222222, 0.77777778,
        0.66666667, 0.88888889, 0.94444444, 1.        ],
       [0.7037037 , 0.74074074, 0.77777778, 0.81481481, 0.85185185,
        0.88888889, 0.92592593, 0.96296296, 1.        ]])

<h1  style="color: blue;">2.	Использование команд библиотеки pandas</h1>

# 2.1.	Импортируйте данные из файла “Global Population Trends(2016-2022).csv”.

In [7]:
import pandas as pd

# 2.2.	 Считайте несколько первых записей таблицы (head())

In [8]:
df = pd.read_csv('Global Population Trends(2016-2022).csv')
df.head()

Country  Year Total Population Urban Population Rural Population  \
0  Afghanistan  2017                -                -                -   
1  Afghanistan  2018       36,686,784        9,353,296       27,333,488   
2  Afghanistan  2019       37,769,499        9,727,157       28,042,342   
3  Afghanistan  2020       38,972,230       10,142,913       28,829,317   
4  Afghanistan  2021       40,099,462       10,551,772       29,547,690   

  Population Density Life Expectancy  Birth Rate  Death Rate Fertility Rate  \
0                 55            63.0      37.342       7.027          5.129   
1                 56            63.0      36.927       6.981          5.002   
2                 58            64.0      36.466       6.791           4.87   
3                 60            63.0      36.051       7.113           4.75   
4                  -            62.0      35.842       7.344          4.643   

  Infant Mortality Rate Growth Rate  
0                  49.4           -  
1                  47.8         3.0  
2                  46.3         3.0  
3                  44.8         3.0  
4                  43.4         3.0

# 2.3.	 Определите размерность данного фрейма (shape())

In [9]:
df.shape

(1073, 12)

# 2.4. Выведите название заголовков столбцов фрейма (columns)

In [10]:
df.columns

Index(['Country', 'Year', 'Total Population', 'Urban Population',
       'Rural Population', 'Population Density', 'Life Expectancy',
       'Birth Rate', 'Death Rate', 'Fertility Rate', 'Infant Mortality Rate',
       'Growth Rate'],
      dtype='object')

# 2.5.	Получите описание всех переменных (полей) (info())

In [11]:
df.info

<bound method DataFrame.info of           Country  Year Total Population Urban Population Rural Population  \
0     Afghanistan  2017                -                -                -   
1     Afghanistan  2018       36,686,784        9,353,296       27,333,488   
2     Afghanistan  2019       37,769,499        9,727,157       28,042,342   
3     Afghanistan  2020       38,972,230       10,142,913       28,829,317   
4     Afghanistan  2021       40,099,462       10,551,772       29,547,690   
...           ...   ...              ...              ...              ...   
1068     Zimbabwe  2017                -                -                -   
1069     Zimbabwe  2018       15,052,184        4,848,158       10,204,026   
1070     Zimbabwe  2019       15,354,608        4,945,719       10,408,889   
1071     Zimbabwe  2020       15,669,666        5,052,214       10,617,452   
1072     Zimbabwe  2021       15,993,524        5,166,388       10,827,136   

     Population Density Life Ex

# 2.6.	 Удалите строки, не содержащие значения в столбце «Total Population» - “-” 

In [26]:
df1 = df[df['Total Population']!='-']
df1

Country  Year Total Population Urban Population Rural Population  \
1     Afghanistan  2018       36,686,784        9,353,296       27,333,488   
2     Afghanistan  2019       37,769,499        9,727,157       28,042,342   
3     Afghanistan  2020       38,972,230       10,142,913       28,829,317   
4     Afghanistan  2021       40,099,462       10,551,772       29,547,690   
6         Albania  2018        2,866,376        1,728,969        1,137,407   
...           ...   ...              ...              ...              ...   
1067       Zambia  2021       19,473,125        8,800,295       10,672,830   
1069     Zimbabwe  2018       15,052,184        4,848,158       10,204,026   
1070     Zimbabwe  2019       15,354,608        4,945,719       10,408,889   
1071     Zimbabwe  2020       15,669,666        5,052,214       10,617,452   
1072     Zimbabwe  2021       15,993,524        5,166,388       10,827,136   

     Population Density Life Expectancy  Birth Rate  Death Rate  \
1                    56            63.0      36.927       6.981   
2                    58            64.0      36.466       6.791   
3                    60            63.0      36.051       7.113   
4                     -            62.0      35.842       7.344   
6                   105            79.0      10.517       8.308   
...                 ...             ...         ...         ...   
1067                  -            61.0      34.511       6.973   
1069                 39            61.0      32.074       7.972   
1070                 40            61.0      31.518       8.043   
1071                 41            61.0      31.009       8.132   
1072                  -            59.0      30.537       9.057   

     Fertility Rate Infant Mortality Rate Growth Rate  
1             5.002                  47.8         3.0  
2              4.87                  46.3         3.0  
3              4.75                  44.8         3.0  
4             4.643                  43.4         3.0  
6              1.44                   8.3         0.0  
...             ...                   ...         ...  
1067          4.308                  40.2         3.0  
1069          3.659                  38.0         2.0  
1070          3.599                  37.1         2.0  
1071          3.545                  36.6         2.0  
1072          3.491                  35.7         2.0  

[864 rows x 12 columns]

# 2.7.	Получите описательную статистику по переменным (например, max(), min(), describe())

In [13]:
df1.describe()

Year  Birth Rate  Death Rate
count   864.000000  864.000000  864.000000
mean   2019.500000   18.548384    7.889123
std       1.118682    9.887518    3.041385
min    2018.000000    0.000000    0.000000
25%    2018.750000   10.500000    6.116500
50%    2019.500000   15.628500    7.453500
75%    2020.250000   25.565000    9.385000
max    2021.000000   46.127000   21.700000

# 2.8.	Выполните сортировку данных по нескольким критериям

In [27]:
df1.loc[:, 'Total Population'] = df1['Total Population'].str.strip() 
df1.loc[:, 'Total Population'] = df1['Total Population'].str.replace(',', '') 
df1.loc[:, 'Total Population'] = pd.to_numeric(df1['Total Population'], errors='coerce')

df_sorted = df1.sort_values(by=["Year", "Total Population"], ascending=[True, False])
df_sorted


Country  Year Total Population Urban Population  \
202                      China  2018       1402760000      829,760,595   
432                      India  2018       1369003306      465,871,825   
1019             United States  2018        326838199      268,844,029   
437                  Indonesia  2018        267066843      147,754,731   
725                   Pakistan  2018        219731479       80,566,744   
...                        ...   ...              ...              ...   
907   St. Martin (French Part)  2021            31948                -   
137     British Virgin Islands  2021            31122           15,225   
733                      Palau  2021            18024           14,686   
664                      Nauru  2021            12511           12,511   
997                     Tuvalu  2021            11204            7,259   

     Rural Population Population Density Life Expectancy  Birth Rate  \
202       572,999,405                149            78.0      10.860   
432       903,131,481                460            71.0      17.651   
1019       57,994,170                 36            79.0      11.600   
437       119,312,112                142            70.0      17.179   
725       139,164,735                285            66.0      28.594   
...               ...                ...             ...         ...   
907                 -                  -            80.0      15.053   
137            15,897                  -            74.0       7.634   
733             3,338                  -               -      13.400   
664                 -                  -            64.0      27.560   
997             3,945                  -            65.0      23.484   

      Death Rate Fertility Rate Infant Mortality Rate Growth Rate  
202        7.080          1.554                   6.4         0.0  
432        6.644          2.177                  29.8         1.0  
1019       8.678           1.73                   5.6         1.0  
437        7.496          2.234                  20.8         1.0  
725        6.843          3.685                  57.4         2.0  
...          ...            ...                   ...         ...  
907        4.911          2.415                     -        -2.0  
137        7.613          1.005                   9.9         1.0  
733       10.200            0.0                  15.1         0.0  
664        6.633          3.519                  23.2         2.0  
997       10.159          3.163                  18.1         1.0  

[864 rows x 12 columns]

# 2.9.	 Выведите название страны, которая имеет максимальную численность населения

In [28]:
df_sorted_byP = df1.sort_values(by="Total Population", ascending=True)
country_max = df_sorted_byP.iloc[-1]["Country"]
country_year = df_sorted_byP.iloc[-1]["Year"]
country_p = df_sorted_byP.iloc[-1]["Total Population"]
print(f'Answer is {country_max} in {country_year} with {country_p} people')

Answer is China in 2021 with 1412360000 people


# 2.10.	Выведите название страны, которая имеет минимальную численность населения

In [29]:
country_min = df_sorted_byP.iloc[0]["Country"]
country_year_min = df_sorted_byP.iloc[0]["Year"]
country_m = df_sorted_byP.iloc[0]["Total Population"]
print(f'Answer is {country_min} in {country_year_min} with {country_m} people')

Answer is Tuvalu in 2018 with 10865 people


# 2.11.	Экспорт фрейма в MS Excel

In [18]:
df1.to_excel("date_frame.xlsx", index=False, engine='openpyxl')
